version: '3.8'

services:
  app:
    build: ../dfs-master-server
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: dfs-master
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dfs-master
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Frontend (React-Vite)
  frontend:
    build: .
    ports:
      - "5173:80"  # Map Vite's default port (5173) to host port 5173
    depends_on:
      - app  # Ensure the backend is up before the frontend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080

volumes:
  postgres-data: